name: hyssop Server
port: 8888
debug: False
doc:
  description: example orm test api
component:
  orm:
    db_1:
      module: 'sqlite_memory'
      connections: 1
  test_entity:
    db_id: db_1
controller:
  /testEntity/?(?P<id>\w+)?:
    enum: test_entity
